
services:
  health-check:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: health-check
    environment:
      - http_proxy=http://123.123.123.123:1234
      - https_proxy=http://123.123.123.123:1234
      - NO_PROXY=host.com
      - HEALTH_CHECK_DOMAINS=https://host.to.check
      - CHECK_INTERVAL=60
      - STATUS_REPORT_INTERVAL=3600
      - TELEGRAM_TOKEN=1234:telegram_bot_token
      - TELEGRAM_CHAT_ID=12345567
    networks:
      - health-net

networks:
  health-net:
    driver: bridge
